# Site settings
title: ir
description: 'Being programmer is all about sharing!'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Irsyad Asyhari Lubis'
  email: irsyad.lubis@gmail.com
  twitter_username: irsyadlubis
  facebook_username: irsyad.lubis@gmail.com
  github_username:  ir210
  linkedin_username:  irsyad.lubis@gmail.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
paginate: 5
paginate_path: 'page:num'

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
